name: CI for Release

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Docker Login
              uses: docker/login-action@v3.3.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}
                      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
    
            - name: Build and push Docker images
              uses: docker/build-push-action@v6.13.0
              with:
                  platforms: linux/amd64,linux/arm64
                  context: .
                  file: ./Dockerfile
                  push: true
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  tags: |
                    ghcr.io/${{ github.repository }}:${{ github.sha }}
                    ghcr.io/${{ github.repository }}:latest